### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by fabricecatherine03** [bluewalk/BMWConnecteDrive#4]
Hello Bluewalk,

The code has worked for a few days but, unfortunately, BMW has probably done some change again. No luck :-(

I have now an issue in this piece of code

  _public function getInfo() {

    $this->_checkAuth();

    $result = $this->_request($this->api_url . sprintf($this::$VEHILCE_INFO, $this->config->vin));

    return $result;
  }_

the $result variable seems to indicate a 404 error. Here is its content (from the serialize function):

O:8:"stdClass":3:{s:7:"headers";s:371:"HTTP/1.1 404 Not Found Date: Tue, 01 Mar 2022 07:58:39 GMT Server: Apache Max-Forwards: 20 Via: 1.0 lpcdapigapp04 () X-CorrelationID: Id-2fd21d62f69fa1beeb3443ce 0; Id-2fd21d62f69fa1beeb3443ce 1 X-Content-Type-Options: nosniff X-Frame-Options: SAMEORIGIN X-XSS-Protection: 1; mode=block Content-Language:  Content-Type: text/html Transfer-Encoding: chunked  ";s:4:"body";N;s:8:"httpCode";s:15:"404 - NOT_FOUND";}

**Comment by bluewalk** [comment]
Hi @fabricecatherine03, I was afraid this would happen, they seem to be phasing out the old API. Guess you will have to use `getVehicles` now, which has a different structure.
