### ISSUE TITLE
Deprecated: getInfo

### ISSUE THREAD

**Issue by sincze** [bluewalk/BMWConnecteDrive#5]
I guess this function is now officially deprecated ??
As this is the result, no more output. Your newest function **getVehicles()** is still working.
```
getInfo
-------------------------------------------------------
<br />
<b>Warning</b>:  Undefined variable $door_lock_state in <b>/bmwall.php</b> on line <b>206</b><br />
door_lock_state 
<br />
<b>Warning</b>:  Undefined variable $door_lock_state in <b>/bmwall.php</b> on line <b>209</b><br />
door_lock_state 
```

**Comment by bluewalk** [comment]
Yes I think they have depricated the api completely now, whereas before it was working spotty at best.

**Comment by sincze** [comment]
Issue csn be closed. Function deprecated.
