### ISSUE TITLE
Seems API is not working anymore.

### ISSUE THREAD

**Issue by sincze** [bluewalk/BMWConnecteDrive#6]
Unfortunately I don't receive any data anymore sincze 25-05-2022 in the morning.

```
getVehicles
<br />
<b>Warning</b>:  Undefined property: stdClass::$access_token in <b>ConnectedDrive.php</b> on line <b>141</b><br />
<br />
<b>Warning</b>:  Undefined property: stdClass::$expires_in in <b>ConnectedDrive.php</b> on line <b>142</b><br />
<br />
<b>Warning</b>:  Undefined property: stdClass::$refresh_token in <b>ConnectedDrive.php</b> on line <b>143</b><br />
<br />
<b>Warning</b>:  Undefined property: stdClass::$id_token in <b>ConnectedDrive.php</b> on line <b>144</b><br />
```

**Comment by bluewalk** [comment]
Hiya,

There has actually been a problem with getting data (returning `null`) due to an outdated user-agent), this has been fixed now.

Your issue seems to be unrelated to this, looks like it can't find your auth.json (or empty object).

Cheers

**Comment by sincze** [comment]
Modified the ConnectedDrive.php to the latest version as mentioned on your Github and it all started working again!. Many thanks,
