### ISSUE TITLE
Mileage in mile in stead of KM

### ISSUE THREAD

**Issue by sincze** [bluewalk/BMWConnecteDrive#7]
Any way we can force the API to spit KM here ??

 [status] => Array
                (
                    [lastUpdatedAt] => 2022-06-22T14:51:41Z
                    [currentMileage] => Array
                        (
                            [mileage] => 12041
                            [units] => mi
                            [formattedMileage] => 12,041
                        )

Mentioned here for reference ;-) and hopefully the solution:
https://github.com/bimmerconnected/bimmer_connected/issues/450

**Comment by bluewalk** [comment]
Not that I know of. I think the app does the conversion (mileage * 1.609344).
